### ISSUE TITLE
sortCitiesArray

### ISSUE THREAD

**Issue by Kalita-Roman** [eneko7/js-assignments#19]
https://github.com/eneko7/js-assignments/blob/af8927a2f9c96cd85c51caf0a84f31a31aedfe2e/task/04-arrays-tasks.js#L483-L505

This [localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) helps improve the solution.

**Comment by eneko7** [comment]
`return arr.sort((a, b) => {
    return (a.country > b.country) - (a.country < b.country)
      || (a.city > b.city) - (a.city < b.city);
  });`
it is my short variant
